"""100 situations for the nix usage quiz.

BRANCH-ONLY, alongside src/telemetry.zig.

A scenario NEVER names the feature that would solve it. The whole measurement
is free recall: if a command does not come to mind unprompted, that is the
finding. Multiple choice would teach the answer and destroy the signal.

Fields:
  id       stable, so answers survive the bank being edited
  s        the situation, as it would actually arrive
  tags     features a good answer might reach for ("" = none exist)
  kind     nix-core | weighed | obscure | ambiguous | cannot | not-first
  note     what nix offers, shown ONLY in the debrief afterwards
"""

Q = [
    # ---- weighed: env.toml -------------------------------------------------
    dict(id=1, kind="weighed", tags=["env"],
         s="A project's commands need API_BASE pointed at your local server, but the value that belongs in the repo is the staging one. You want every command you run in that project to see yours.",
         note="`.nix/env.toml` [env] committed, `~/.nix/env/<alias>.toml` as the private per-machine override (it wins)."),
    dict(id=2, kind="weighed", tags=["env", "secret"],
         s="A build needs a token. It must not end up in any file that gets committed.",
         note="`${secret:NAME}` in env.toml or an action, value stored via `nix --secret set NAME` in Windows Credential Manager."),
    dict(id=3, kind="weighed", tags=["env"],
         s="A command in a project is behaving as if some variable is wrong. You want to see exactly what it will get, and where each value came from.",
         note="`nix <alias> --env` prints the merged environment with provenance and no secret values."),
    dict(id=4, kind="weighed", tags=["env", "trust"],
         s="You cloned a teammate's repo. The first command you run in it stops and asks you something before doing anything.",
         note="The provenance gate: a cloned .nix/env.toml or actions.toml needs `nix --trust <alias>` (or an inline y)."),
    dict(id=5, kind="weighed", tags=["env"],
         s="The same variable name is set in your shell and in a project's config. You need to know which one wins before you run anything.",
         note="`nix <alias> --env` shows the merged result and which layer supplied each value."),

    # ---- weighed: deps -----------------------------------------------------
    dict(id=6, kind="weighed", tags=["deps"],
         s="hoot has to be rebuilt before gaze, and gaze before you can run the demo. You want one command that does all three in the right order.",
         note="`[deps] needs = [...]` in each project's actions.toml, then `x <alias> --deps :build`."),
    dict(id=7, kind="weighed", tags=["deps"],
         s="You split a shared library out of a repo. Three other projects now build against it and must build after it.",
         note="Declare `[deps] needs = [\"<lib-alias>\"]` in each of the three."),
    dict(id=8, kind="weighed", tags=["deps"],
         s="A multi-repo build stops immediately, complaining about something that isn't registered. You want the full list of what's broken, not the first one it hit.",
         note="The --deps pre-flight collects every unknown edge and reports them together."),
    dict(id=9, kind="weighed", tags=["deps"],
         s="Two of your projects each depend on the same third one. You want it built once, early enough for both.",
         note="The dependency walk dedupes on the way out, so a diamond builds once at the earliest correct point."),

    # ---- weighed: secrets --------------------------------------------------
    dict(id=10, kind="weighed", tags=["secret"],
         s="An action connects to a database. The password is currently sitting in plain text in a file you're about to commit.",
         note="`nix --secret set NAME`, then reference it as `${secret:NAME}`."),
    dict(id=11, kind="weighed", tags=["secret"],
         s="You want to know which credentials this machine has stored for your tooling, without any of the values appearing on screen.",
         note="`nix --secret list` - names only, never values."),
    dict(id=12, kind="weighed", tags=["secret"],
         s="A token you use in an action expired this morning and you have the new one.",
         note="`nix --secret set NAME` again (overwrites); `nix --secret rm NAME` to drop it."),

    # ---- weighed: --as dialects -------------------------------------------
    dict(id=13, kind="weighed", tags=["as"],
         s="You're writing a WSL command line and need the path to the playground project in the form WSL understands.",
         note="`nix play --as wsl` (or `y play --as wsl` to copy it)."),
    dict(id=14, kind="weighed", tags=["as"],
         s="You want to send a colleague a link to a folder on this machine that they can click.",
         note="`nix <alias> --as uri` produces a percent-encoded file:// URL."),
    dict(id=15, kind="weighed", tags=["as"],
         s="A Git Bash script needs a project's path written the way Git Bash spells drives.",
         note="`nix <alias> --as gitbash` -> /c/... ."),
    dict(id=16, kind="weighed", tags=["as"],
         s="You want to cd into a project, but spelled for a different tool than the one you're in.",
         note="Trick question: `o` refuses --as. It navigates rather than printing, so a translated path would be broken, not differently spelled."),

    # ---- weighed: time ledger ---------------------------------------------
    dict(id=17, kind="weighed", tags=["time"],
         s="It's Friday. You want a rough sense of how much of the week went into the overlay project versus nix itself.",
         note="`nix --time` - passive per-alias time from session/run/action boundaries."),
    dict(id=18, kind="weighed", tags=["time"],
         s="You feel like today disappeared into one project and want to check whether that's true.",
         note="`nix --time --day`."),
    dict(id=19, kind="weighed", tags=["time"],
         s="You want the whole recorded history for one project, not just this week.",
         note="`nix --time <alias> --all`."),

    # ---- weighed: logs / flight recorder -----------------------------------
    dict(id=20, kind="weighed", tags=["logs"],
         s="A test run failed twenty minutes ago. You've since closed that terminal and you want to read what it printed.",
         note="`nix --logs` browses ~/.nix/logs - but only if recording was on."),
    dict(id=21, kind="weighed", tags=["logs"],
         s="You want every build you run from now on to keep its output somewhere you can go back to.",
         note="`[log] actions = true` in config.toml (default is OFF - teeing costs the child its colour)."),
    dict(id=22, kind="weighed", tags=["logs"],
         s="This one run is going to matter and you want its output kept, without turning recording on generally.",
         note="`--log` on that invocation; `--no-log` is the inverse."),

    # ---- weighed: action palette ------------------------------------------
    dict(id=23, kind="weighed", tags=["palette"],
         s="You open a project you set up four months ago. You cannot remember what you wired up to run in it.",
         note="`x <alias> :` lists that project's actions; from any command, actually (`o <alias> :`)."),
    dict(id=24, kind="weighed", tags=["palette"],
         s="You want to see everything runnable across every project you have, in one place, and start one of them.",
         note="`nix --actions` / `-A`, or a bare leading `:` from any wrapper (`x :`)."),
    dict(id=25, kind="weighed", tags=["palette", "edit"],
         s="An action does the wrong thing and you want to open the file where it's declared, at that line.",
         note="`e <alias> :<name>` opens the declaration at its line."),
    dict(id=26, kind="weighed", tags=["palette"],
         s="You keep wanting the same little command available no matter which project you're standing in.",
         note="`~/.nix/actions/_default.toml` - lowest precedence, reachable as `x <any-alias> :<name>`."),

    # ---- weighed: watch ----------------------------------------------------
    dict(id=27, kind="weighed", tags=["watch"],
         s="You're iterating on a parser and want the tests to run again every time you save.",
         note="`x <alias> --watch :test` - finish-then-rerun, any command."),
    dict(id=28, kind="weighed", tags=["watch"],
         s="A rerun-on-change loop keeps retriggering itself because the run writes into the directory it's watching.",
         note="`[watch] exclude` adds paths on top of watch's own defaults."),

    # ---- weighed: notes ----------------------------------------------------
    dict(id=29, kind="weighed", tags=["notes"],
         s="You're stopping mid-refactor for the day and want to leave yourself the one sentence that would let you pick it up cold.",
         note="`n <alias> <text>` appends to ~/.nix/notes/<alias>.md."),
    dict(id=30, kind="weighed", tags=["notes"],
         s="Weeks ago you wrote down why you'd blocked on something. You remember the phrase but not which project it was.",
         note="`nix --notes <pattern>` searches every alias's notes in one view."),
    dict(id=31, kind="weighed", tags=["notes"],
         s="You come back to a project and want to read whatever past-you left about it.",
         note="`n <alias>` reads that alias's notes."),

    # ---- weighed: segments -------------------------------------------------
    dict(id=32, kind="weighed", tags=["segments"],
         s="You are forever navigating into the same subdirectory of one project, and typing the tail of the path every time.",
         note="A `[[contexts]]` segment with a source-template, then `seg@alias`."),
    dict(id=33, kind="weighed", tags=["segments", "context"],
         s="You want a shortcut that lands you in a folder whose name depends on something only a script can work out - a ticket's owner, say.",
         note="A `[[contexts]]` block with a `run` line: the script returns variables that feed the source-template."),
    dict(id=34, kind="weighed", tags=["segments", "context"],
         s="A script that computes where to go has several equally good answers and you want to pick among them.",
         note="A context source may return several blocks - nix shows them as a menu (#19)."),
    dict(id=35, kind="weighed", tags=["segments", "context", "secret"],
         s="A context script has to authenticate to answer, and you don't want the credential landing in any child environment it shouldn't.",
         note="A context source can declare a variable secret (#51)."),

    # ---- weighed: groups ---------------------------------------------------
    dict(id=36, kind="weighed", tags=["groups"],
         s="Monday morning: you want to pull the latest in every work repo without visiting them one at a time.",
         note="`x +work git pull` - the group fan-out."),
    dict(id=37, kind="weighed", tags=["groups"],
         s="You want to search one phrase across two related repos at the same time and open whichever hit matters.",
         note="`g +<group> <pattern>` - one picker over all roots."),
    dict(id=38, kind="weighed", tags=["groups"],
         s="You want to add a project to a set you already fan commands across.",
         note="`nix <member>+<group>` (and `--remove` to drop it)."),

    # ---- weighed: bin exports ---------------------------------------------
    dict(id=39, kind="weighed", tags=["bin"],
         s="You just finished building a small tool and want to run it by its bare name from anywhere, without touching PATH by hand.",
         note="`[bin] name = \"zig-out/bin/tool.exe\"` in the project's actions.toml, then `nix --sync-bin`."),
    dict(id=40, kind="weighed", tags=["bin"],
         s="You keep typing the same long invocation to start one specific thing, dozens of times a week, from wherever you happen to be.",
         note="`[bin] short = \":action\"` makes a global command that runs that action in the alias dir."),
    dict(id=41, kind="weighed", tags=["bin"],
         s="You moved a repo to a new drive and a global command that came from it stopped working.",
         note="`nix --sync-bin` reinstalls from the alias, which followed the move; `--doctor` reports the drift."),

    # ---- weighed: provenance ----------------------------------------------
    dict(id=42, kind="weighed", tags=["trust"],
         s="You cloned a repo that ships its own scripts. Running one of them refuses outright, and you're in a shell that can't ask you anything.",
         note="`nix --trust <alias>` approves the files as they stand; without a console the gate refuses rather than prompting."),
    dict(id=43, kind="weighed", tags=["trust"],
         s="You edited your own project's actions file and the next run asks you to approve it again.",
         note="Expected: the approval is over the exact bytes, so an edit re-arms it. This is the friction we measured as ~90% self-inflicted."),

    # ---- obscure: diagnostics ---------------------------------------------
    dict(id=44, kind="obscure", tags=["doctor"],
         s="Something about your setup is off - a command isn't found, or a path looks wrong - and you want one place that tells you what nix thinks is true.",
         note="`nix --doctor` (`-q` for problems only, `--json` for a machine-readable report)."),
    dict(id=45, kind="obscure", tags=["sweep"],
         s="The directory picker is drowning in node_modules and build output.",
         note="`nix --sweep` finds noisy trees to exclude from the picker."),
    dict(id=46, kind="obscure", tags=["prune"],
         s="Several aliases point at folders you deleted months ago.",
         note="`nix --prune` removes stale aliases interactively."),
    dict(id=47, kind="obscure", tags=["picker-check"],
         s="A folder you expect to see in the picker never appears and you want to know why.",
         note="`nix --picker-check <name>` replays the real pipeline as a diagnostic."),
    dict(id=48, kind="obscure", tags=["which"],
         s="You're several folders deep in something and want to know which registered project you're actually inside.",
         note="`nix --which` (defaults to cwd)."),
    dict(id=49, kind="obscure", tags=["self-alias"],
         s="You want to open nix's own configuration to change something.",
         note="`o .nix` / `e .nix` - `.nix` is a built-in alias for nix's home, so config never needs an absolute path."),
    dict(id=50, kind="obscure", tags=["list-names", "json"],
         s="You're writing a script that has to iterate over every alias you have.",
         note="`nix --list-names` (bare names, the form to parse); `--json` where a command has it."),
    dict(id=51, kind="obscure", tags=["quit"],
         s="You've stacked four subshells navigating around and want to be back where you started.",
         note="`q` closes the shell it runs in. (Forward-only by design - there is no back-navigation.)"),
    dict(id=52, kind="obscure", tags=["force"],
         s="You're registering a name that already points somewhere else, and you mean it.",
         note="`--force`. Deliberately NOT implied by --no-prompt: 'don't block me' and 'overwrite what I have' are different statements."),
    dict(id=53, kind="obscure", tags=["no-prompt"],
         s="You're calling nix from a script and it must never open a picker or wait for an answer.",
         note="`--no-prompt` prints what it would have offered and acts on nothing."),
    dict(id=54, kind="obscure", tags=["shortcuts"],
         s="One of nix's one-letter commands collides with something else you use constantly.",
         note="`[shortcuts]` in config.toml renames a builtin slot, then `nix --sync`."),
    dict(id=55, kind="obscure", tags=["notify"],
         s="A build takes four minutes and you always tab away and forget about it.",
         note="`[notify] on_finish` - hoot fires when a foreground action finishes."),
    dict(id=56, kind="obscure", tags=["notify"],
         s="Those finish notifications are firing for trivial actions and you've started ignoring them.",
         note="The notify skip-list: actions not worth a toast (#50)."),
    dict(id=57, kind="obscure", tags=["scripts"],
         s="A project has a handful of PowerShell scripts you run often, and you don't want to spell out the interpreter and the path each time.",
         note="Put them in `.nix/scripts/` - `x <alias> <bare-name>` finds and wraps them; they're also on PATH inside an `o` session."),
    dict(id=58, kind="obscure", tags=["sudo"],
         s="One action has to run elevated.",
         note="An action whose command starts with `sudo` runs elevated in its own console - it raises UAC, so it can never run unattended."),
    dict(id=59, kind="obscure", tags=["args"],
         s="You want one action to take a different argument each time you run it, without writing five near-identical actions.",
         note="`x <alias> :test -- --json`; args are appended or substituted into an `{args}` placeholder."),
    dict(id=60, kind="obscure", tags=["chain"],
         s="You want build then test, stopping if build fails, without writing a third action that calls both.",
         note="`x <alias> :build :test` - chained in order, stops at the first failure."),
    dict(id=61, kind="obscure", tags=["backup"],
         s="You're setting up a second machine and want your aliases and actions there.",
         note="Restore ~/.nix from snapshot backup. nix itself keeps state in ~/.nix."),

    # ---- ambiguous: several defensible routes ------------------------------
    dict(id=62, kind="ambiguous", tags=["yank", "as"],
         s="You need a project's path in your clipboard to paste into a dialog box.",
         note="`y <alias>`. The one you flagged as least-used but still frequent."),
    dict(id=63, kind="ambiguous", tags=["yank"],
         s="You need three specific files out of a project attached to a message.",
         note="`y <alias> <pattern>` copies the real files (CF_HDROP), not just the path."),
    dict(id=64, kind="ambiguous", tags=["paste"],
         s="You've got a screenshot on the clipboard and want it saved into a project folder.",
         note="`p <alias> [name]`."),
    dict(id=65, kind="ambiguous", tags=["explore", "yank"],
         s="You want to look at a project's folder in Explorer.",
         note="`s <alias>`."),
    dict(id=66, kind="ambiguous", tags=["run", "palette"],
         s="You want to run a project's test suite, and you're standing in a completely different project.",
         note="`x <alias> :test` from anywhere - no cd needed."),
    dict(id=67, kind="ambiguous", tags=["run"],
         s="You're already standing in the project and want to run its build.",
         note="A leading bare `:build` runs it in the current directory - no alias needed."),
    dict(id=68, kind="ambiguous", tags=["grep"],
         s="You need every place a particular function is called across one repo, and to open a few of them.",
         note="`g <alias> <pattern>`."),
    dict(id=69, kind="ambiguous", tags=["grep"],
         s="The thing you're looking for is inside a PDF and some office documents, not source files.",
         note="`g <alias> <pat> --all` routes through rga."),
    dict(id=70, kind="ambiguous", tags=["find"],
         s="You know roughly what a file is called but not where it lives in the repo.",
         note="`f <alias> [pattern]`."),
    dict(id=71, kind="ambiguous", tags=["navigate"],
         s="You want a shell sitting in a project, with that project's own scripts available by name.",
         note="`o <alias>` stacks a subshell with .nix/scripts on PATH."),
    dict(id=72, kind="ambiguous", tags=["navigate", "picker"],
         s="You want to go to a folder that you've never registered and whose path you'd have to hunt for.",
         note="`o <name>` misses, offers the directory picker, and registers what you pick."),
    dict(id=73, kind="ambiguous", tags=["edit"],
         s="You want a project open in your editor.",
         note="`e <alias> [file]`."),
    dict(id=74, kind="ambiguous", tags=["run", "bin"],
         s="A command you run constantly lives in one project but you want it everywhere.",
         note="Two real answers: a `[bin]` export, or a `_default.toml` action. Which you reach for is the interesting part."),
    dict(id=75, kind="ambiguous", tags=["groups", "run"],
         s="You want to check the git status of everything you have on the go.",
         note="`x +<group> git status` - or one at a time, which is the comparison."),
    dict(id=76, kind="ambiguous", tags=["notes", "logs"],
         s="You want to remember what went wrong in a build you ran yesterday.",
         note="Two different tools: a note you wrote, or a recording nix kept. Which you assume exists says a lot."),
    dict(id=77, kind="ambiguous", tags=["time", "usage"],
         s="You want to know which projects you actually worked on this month.",
         note="`nix --time --all`, or `nix --list` ordering by usage - different questions, both defensible."),
    dict(id=78, kind="ambiguous", tags=["env", "secret"],
         s="A command needs one value that changes per machine and one that must stay secret.",
         note="env.toml for the first, `${secret:}` for the second - they compose."),
    dict(id=79, kind="ambiguous", tags=["palette", "notes"],
         s="You want to leave a hint for future-you about how to run something unusual in a project.",
         note="An action with a `#` description above it (nix shows it in the palette), or a note. Both work."),
    dict(id=80, kind="ambiguous", tags=["watch", "run"],
         s="You want a command run repeatedly while you work, but only after each run finishes.",
         note="`--watch` is finish-then-rerun by design."),
    dict(id=81, kind="ambiguous", tags=["deps", "chain"],
         s="Two projects have to build in a fixed order, and you'd rather not encode that in a script.",
         note="`[deps]`, or a chained `x a :build` then `x b :build`. Both defensible."),

    # ---- nix cannot do this today -----------------------------------------
    dict(id=82, kind="cannot", tags=[],
         s="You want to go back to the directory you were in before the last jump.",
         note="Not offered, on purpose: nix is exact and forward-only, with no back-navigation."),
    dict(id=83, kind="cannot", tags=[],
         s="You type an alias slightly wrong and want nix to work out what you meant.",
         note="Deliberately refused: no fuzzy or frecency guessing. An exact miss opens the picker instead."),
    dict(id=84, kind="cannot", tags=[],
         s="You want a project's build to run automatically at 6am every weekday.",
         note="No scheduling in nix. Task Scheduler, or a cron-shaped tool."),
    dict(id=85, kind="cannot", tags=[],
         s="You want to run an action on a different machine.",
         note="No remote execution."),
    dict(id=86, kind="cannot", tags=[],
         s="Your aliases on the laptop and the desktop have drifted and you want them to stay in step by themselves.",
         note="No built-in sync. Restore from snapshot backup."),
    dict(id=87, kind="cannot", tags=[],
         s="You want to watch for changes in a directory that isn't inside the alias you're running from.",
         note="--watch watches the alias dir."),
    dict(id=88, kind="cannot", tags=[],
         s="You removed an alias and immediately wish you hadn't.",
         note="No undo. Re-register it, or restore from snapshot backup."),
    dict(id=89, kind="cannot", tags=[],
         s="You want to rename an alias, keeping everything attached to it.",
         note="No rename: register the new name and remove the old. Notes/actions keyed on the name do not follow."),
    dict(id=90, kind="cannot", tags=[],
         s="You want a group's members to build in parallel to save wall-clock time.",
         note="Fan-out is sequential, and --deps is ordered by design."),
    dict(id=91, kind="cannot", tags=[],
         s="You want to watch a long action's output live from another terminal while it runs.",
         note="Recordings are written for reading afterwards, not tailed."),
    dict(id=92, kind="cannot", tags=[],
         s="You want one project's action to be callable by a teammate without them cloning the repo.",
         note="Actions are local; sharing means the repo (and the trust gate)."),
    dict(id=93, kind="cannot", tags=[],
         s="You want nix to pick a default action so a bare command in a project 'just runs the thing'.",
         note="No default action - a bare `:` lists, it does not choose."),

    # ---- nix would not be the first thing to reach for --------------------
    dict(id=94, kind="not-first", tags=[],
         s="You want to see what's changed in the repo you're currently sitting in.",
         note="`git status`. nix has nothing to add."),
    dict(id=95, kind="not-first", tags=[],
         s="You already have a file's full path and want to open it.",
         note="Open it. Reaching for an alias here is a detour."),
    dict(id=96, kind="not-first", tags=[],
         s="A process is stuck and you want it gone.",
         note="Task manager or a kill command - though you do have a qkill script."),
    dict(id=97, kind="not-first", tags=[],
         s="You want to know how much space is left on the drive.",
         note="Outside nix entirely."),
    dict(id=98, kind="not-first", tags=[],
         s="You want to install a tool you don't have yet.",
         note="Scoop, on this machine."),
    dict(id=99, kind="not-first", tags=[],
         s="You want to read a log file whose path is already on your screen.",
         note="Just open it."),
    dict(id=100, kind="not-first", tags=[],
         s="You want to know what a command's flags do.",
         note="`--help`, or `--agent` for the full spec - but reaching for the docs is the normal move."),
]
