//! ~/.nix/AGENTS.md generation — an agent-facing guide to the installed
//! command surface, written by --init/--sync alongside the shell snippet.
//!
//! The guide describes a whole MACHINE's command surface, so it is an installed
//! artifact: written by --init on machines whose owner installed nix, kept in
//! step with [shortcuts] renames by --sync, and never shipped in a clone, where
//! an agent would read it without the owner's consent. nix never wires it into
//! an agent's config; the README shows the one-line import.
//!
//! The repo's own AGENTS.md is contributor documentation scoped to this
//! repository.

const std = @import("std");
const Io = std.Io;
const config = @import("config.zig");
const agentdocs = @import("agentdocs.zig");
const util = @import("util.zig");

pub fn path(arena: std.mem.Allocator, home: []const u8) ![]const u8 {
    return std.fs.path.join(arena, &.{ home, "AGENTS.md" });
}

pub fn write(arena: std.mem.Allocator, io: Io, home: []const u8, cfg: config.Config) !void {
    const p = try path(arena, home);
    try util.writeFileAtomic(arena, io, p, try render(arena, cfg));
}

/// commandTable renders the command rows from the agentdocs spec table, so this
/// guide and `nix --help` describe the same commands the same way. The safety
/// tier is included here, in the always-loaded guide, not only in the
/// on-demand spec.
fn commandTable(arena: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(arena, "| Command | Meaning | Agent |\n|---|---|---|\n");
    var buf: [config.builtinShortcuts().len]*const agentdocs.Spec = undefined;
    for (agentdocs.wrapperSpecs(&buf)) |s| {
        try b.print(arena, "| `{s} {s}` | {s} | {s} |\n", .{
            config.shortcutFor(cfg, s.slot), s.args, s.summary, s.safety.label(),
        });
    }
    return b.items;
}

/// render produces the guide with the machine's effective command names, so a
/// `[shortcuts] s = "show"` rename shows agents `show acme`, not a dead `s`.
pub fn render(arena: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.print(arena,
        \\<!-- Generated by `nix --sync`; edits are overwritten. Command names
        \\     reflect this machine's config.toml [shortcuts]. -->
        \\
        \\# nix directory aliases - agent guide
        \\
        \\This machine uses [nix](https://github.com/sadirano/nix): projects have short
        \\aliases, and navigating, running and searching go through them. Tell the user
        \\nix forms, not cd/absolute paths ("run it with `{[x]s} acme :deploy`").
        \\
        \\{[table]s}
        \\`{[x]s} <alias> :<name>` runs a saved action (`{[x]s} <alias> :` lists them);
        \\`docs@acme` is a sub-alias segment; `nix <name> <path>` registers an alias.
        \\`shared@<alias>` is the project's handoff drop: resolve "the shared" with
        \\`nix shared@<alias>`, never by searching the disk, and keep it out of git.
        \\
        \\**Full spec per command: `<cmd> --agent`, or `nix --agent <topic>`** (bare
        \\`nix --agent` lists topics: actions, env, segments, state, ...).
        \\
        \\## Rules
        \\
        \\1. Never run `{[q]s}`: it closes the shell it runs in. Suggest it only.
        \\2. In your own shell, resolve (`nix <alias>`), don't `{[o]s}`; `{[x]s} <alias> <cmd>`
        \\   works. `nix --list` / `nix --which [path]` find aliases; don't invent
        \\   names. `.nix` is built in and names nix's own home.
        \\3. Check `nix --no-prompt --actions` before writing a command line. A
        \\   recurring command belongs in the project's `.nix/actions.toml`
        \\   (`nix --agent actions`). A new or edited project file will not run for
        \\   you until the user runs `nix --trust <alias>`; that is theirs, not yours.
        \\4. Pickers (`{[g]s}`, `{[f]s}`, patterned `{[s]s}`/`{[y]s}`, `--actions`) block:
        \\   put `--no-prompt` BEFORE the action flag
        \\   (`nix <alias> --no-prompt --grep <pat>`).
        \\5. Don't edit ~/.nix state unasked. Registering an existing name REPOINTS
        \\   it, so check `nix --list` first.
        \\6. When you would hand the user a command to paste, write
        \\   `~/.nix/jobs/<alias>/<name>.<ext>` instead, with
        \\   `# nix: uses=N - <what it does>` first; give them `{[x]s} <alias> :<name>`.
        \\   The first run shows the script and asks. Full spec: `nix --agent jobs`.
        \\
    , .{
        .table = try commandTable(arena, cfg),
        .o = config.shortcutFor(cfg, "o"),
        .s = config.shortcutFor(cfg, "s"),
        .y = config.shortcutFor(cfg, "y"),
        .x = config.shortcutFor(cfg, "x"),
        .g = config.shortcutFor(cfg, "g"),
        .f = config.shortcutFor(cfg, "f"),
        .q = config.shortcutFor(cfg, "q"),
    });
    return b.items;
}

test "render stays small enough to load into every agent session" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const out = try render(arena_state.allocator(), .{});
    try std.testing.expect(out.len < 3000);
}

test "render uses default names" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const out = try render(arena_state.allocator(), .{});
    try std.testing.expect(std.mem.indexOf(u8, out, "| `o <alias> [path]` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`x <alias> :<name>`") != null);
    // The table carries the safety tier, and the guide points at the specs.
    try std.testing.expect(std.mem.indexOf(u8, out, "| user-surface |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`<cmd> --agent`") != null);
}

test "render honours [shortcuts] renames" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const cfg = config.Config{ .shortcuts = &.{
        .{ .builtin = "s", .custom = "show" },
        .{ .builtin = "x", .custom = "run" },
    } };
    const out = try render(arena_state.allocator(), cfg);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `show <alias> [pat]` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `run <alias> <cmd...>` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`run acme :deploy`") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `s <alias>") == null);
}
