//! ~/.nix/AGENTS.md generation — an agent-facing guide to the installed
//! command surface, written by --init/--sync alongside the shell snippet.
//!
//! The guide is an *installed artifact*, and what it describes is why: a whole
//! MACHINE's command surface. Instructions for driving someone's machine have
//! no business arriving in a clone, auto-read by their agent the moment they
//! fetch a directory alias manager - that is the wrong consent model, and it
//! reads as prompt injection. So this one is written by --init and exists only
//! on machines whose owner installed nix, with --sync keeping it honest about
//! [shortcuts] renames. nix never wires it into any agent's config - the README
//! shows the one-line import users add themselves.
//!
//! The repo's own AGENTS.md is a different thing and not a contradiction: it is
//! contributor documentation, scoped to this repository, no wider than the
//! checkout it travels in. The rule is about SCOPE, not about the filename.

const std = @import("std");
const Io = std.Io;
const config = @import("config.zig");
const agentdocs = @import("agentdocs.zig");
const util = @import("util.zig");

pub fn path(arena: std.mem.Allocator, home: []const u8) ![]const u8 {
    return std.fs.path.join(arena, &.{ home, "AGENTS.md" });
}

pub fn write(arena: std.mem.Allocator, io: Io, home: []const u8, cfg: config.Config) !void {
    const p = try path(arena, home);
    try util.writeFileAtomic(arena, io, p, try render(arena, cfg));
}

/// commandTable renders the command rows from the agentdocs spec table, so this
/// guide and `nix --help` describe the same commands the same way. The safety
/// tier rides along: it is the one thing an agent needs before deciding whether
/// to run something, and it belongs in the always-loaded guide rather than only
/// in the on-demand spec.
fn commandTable(arena: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(arena, "| Command | Meaning | Agent |\n|---|---|---|\n");
    var buf: [config.builtinShortcuts().len]*const agentdocs.Spec = undefined;
    for (agentdocs.wrapperSpecs(&buf)) |s| {
        try b.print(arena, "| `{s} {s}` | {s} | {s} |\n", .{
            config.shortcutFor(cfg, s.slot), s.args, s.summary, s.safety.label(),
        });
    }
    return b.items;
}

/// render produces the guide with the machine's effective command names, so a
/// `[shortcuts] s = "show"` rename shows agents `show acme`, not a dead `s`.
pub fn render(arena: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.print(arena,
        \\<!-- Generated by `nix --sync`; edits are overwritten. Command names
        \\     reflect this machine's config.toml [shortcuts]. -->
        \\
        \\# nix directory aliases - agent guide
        \\
        \\The user of this machine navigates with [nix](https://github.com/sadirano/nix),
        \\a directory alias manager: projects get short aliases, and navigation,
        \\running, searching, and file movement go through them. When telling the user
        \\how to open, run, or find something, prefer the nix syntax below over raw
        \\cd/absolute-path instructions - e.g. "I added a deploy action; run it with
        \\`{[x]s} acme :deploy`".
        \\
        \\## Commands (what the user types)
        \\
        \\{[table]s}
        \\Extras: `{[x]s} <alias> :<name>` runs a saved action (`{[x]s} <alias> :` lists
        \\them); `{[o]s} docs@acme` resolves a sub-alias segment; `+group` fans a command
        \\across a set of aliases (`{[x]s} +work git pull`); `nix <name> <path>` registers
        \\a new alias.
        \\
        \\`{[q]s}` is the exception to everything below: it closes the shell it
        \\runs in, so running it yourself ends your own session mid-task. Suggest
        \\it, never call it.
        \\
        \\**Every command has a full spec for you: `<cmd> --agent`** (or
        \\`nix --agent <topic>`; bare `nix --agent` lists the topics). Each one states
        \\whether you may run the command yourself and gives the non-interactive form.
        \\
        \\## Guidance for agents
        \\
        \\1. **Suggest nix forms.** When work produces something runnable or openable,
        \\   give the user the nix one-liner: `{[x]s} <alias> :test`,
        \\   `{[e]s} <alias> src/main.zig`, `{[s]s} <alias> report.pdf`, `{[g]s} <alias> TODO`.
        \\2. **Discover aliases before suggesting.** `nix --list` prints every alias
        \\   with its path; `nix --list-names` prints bare names; `nix <alias>` resolves
        \\   one to its absolute path; `nix --which [path]` prints the alias containing
        \\   a path (default: cwd) - and inside a `{[x]s}`/`{[o]s}` session `$NIX_ALIAS` /
        \\   `$NIX_ALIAS_PATH` are already set. Use the alias that maps to the directory
        \\   you worked in - don't invent names. If none covers it, suggest registering
        \\   one: `nix <name> <path>`.
        \\3. **Prefer saved actions for repeatable commands.** `nix --no-prompt --actions`
        \\   lists every action already wired up on this machine (alias, name,
        \\   command, description) - check there before writing a command line
        \\   of your own. A bare `:` after any command is the interactive
        \\   shorthand for it (`{[x]s} :`), and `<cmd> <alias> :` narrows it to
        \\   one project (`{[o]s} acme :` and `{[x]s} acme :` are the same
        \\   question) - both print rather than open a picker when nobody can
        \\   answer, so they are safe to run yourself. `{[e]s} acme :` is not:
        \\   from the editor the same question CREATES the project's
        \\   .nix/actions.toml from a template when there is nothing to list.
        \\   If a project needs a
        \\   recurring build/test/serve/deploy command, add it to the project's
        \\   `.nix/actions.toml` under `[actions]` - with a `#` comment above it,
        \\   which nix shows as the action's description - and point the user at
        \\   `{[x]s} <alias> :<name>`. Full scripts go in the project's `.nix/scripts/`
        \\   and run by bare name: `{[x]s} <alias> build`. Personal machine-wide
        \\   actions live in `~/.nix/actions/_default.toml` (lowest precedence,
        \\   available via `{[x]s} <any-alias> :<name>`). A tool the project
        \\   builds that should be runnable from anywhere goes under `[bin]` in
        \\   the same actions.toml (e.g. `hoot = "zig-out/bin/hoot.exe"`);
        \\   `nix --sync-bin` installs it into `~/.nix/bin`, which is on PATH.
        \\   A `[bin]` value may instead name one of the file's own actions
        \\   (`ship = ":deploy"`), which makes `ship` a global command running
        \\   that action in the alias dir - arguments and all - from anywhere.
        \\   One bare action name only: flags and chains are refused. In
        \\   `~/.nix/actions/_default.toml` the same line makes a personal
        \\   global that runs in the CURRENT directory. An export whose action
        \\   lives in a committed actions.toml will not install until the user
        \\   runs `nix --trust <alias>`.
        \\   Actions take arguments (`{[x]s} <alias> :test -- --json`, appended or
        \\   substituted into an `{{args}}` placeholder) and chain in order,
        \\   stopping at the first failure (`{[x]s} <alias> :build :test`). An
        \\   action whose command begins with `sudo` runs ELEVATED in its own
        \\   console - it raises a UAC prompt only the user can answer, so never
        \\   put one in a command you expect to run unattended.
        \\   A project's `.nix/actions.toml` and `.nix/scripts/` are gated: the
        \\   first run of an unapproved file shows the command and asks, and
        \\   without a console (an agent's shell) it refuses instead. So an action
        \\   you just wrote will NOT run for you until the user approves it with
        \\   `nix --trust <alias>` - that is the check working, not a bug, and
        \\   `--trust` is never yours to run. Files under `~/.nix` are not gated.
        \\   A project can declare `[deps] needs = ["other-alias"]`, and
        \\   `{[x]s} <alias> --deps :build` then runs each dependency's own
        \\   `:build` first, in order, aborting up front if any of them lacks it.
        \\   Configuration the commands NEED goes in `.nix/env.toml` under
        \\   `[env]`, and is set for every `{[x]s} <alias> ...` and every
        \\   `{[o]s} <alias>` session (`~/.nix/env/<alias>.toml` is the private
        \\   per-machine override, and it wins). Same trust gate as actions.toml,
        \\   so a file you just wrote will not inject until the user approves it.
        \\   Credentials belong there as `${{secret:NAME}}` references, never as
        \\   literal values in a committed file; `nix <alias> --env` prints the
        \\   merged result with provenance and no secret values.
        \\4. **Read the alias's notes when picking up unfamiliar work.**
        \\   `nix --no-prompt --notes [pat]` prints every captured line as
        \\   `<alias>.md:<line>:<text>` and opens nothing. It is where the user
        \\   records "blocked on X, resume at Y", and often the only explanation
        \\   for why a project is mid-change. `nix <alias> --no-prompt --notes`
        \\   narrows that to one alias (what the user types as `{[n]s} <alias>`).
        \\   WRITING is theirs: `nix <alias> --note <text>` (`{[n]s} <alias>
        \\   <text>`) captures their working memory in their words, so add one
        \\   only when asked.
        \\5. **In your own shell, resolve - don't `{[o]s}`.** `{[o]s}` is shell glue that
        \\   cds the user's interactive shell; in an agent's shell run `nix <alias>`
        \\   to get the path, then use the absolute path. `{[x]s} <alias> <cmd>` works
        \\   fine from agent shells.
        \\6. **Add `--no-prompt` instead of avoiding the pickers.** `{[g]s}`, `{[f]s}`,
        \\   patterned `{[s]s}`/`{[y]s}`, `nix --actions`, `nix --notes`, and `nix --prune`/`--sweep` open fzf and would block a
        \\   non-interactive shell. With `--no-prompt` they print what they would have
        \\   offered and act on nothing: `nix <alias> --no-prompt --grep <pat>`,
        \\   `nix <alias> --no-prompt --find <pat>`. The flag goes BEFORE the action
        \\   flag - everything after it belongs to the search tool. `{[o]s} +group` and
        \\   `{[p]s} +group` have no non-interactive form and refuse to run.
        \\7. **Don't touch nix state destructively.** Never edit or delete `~/.nix`
        \\   contents (`aliases.toml`, `groups.toml`, `usage`, ...) unless explicitly
        \\   asked; adding a project-local `.nix/actions.toml`, `.nix/env.toml`
        \\   or `.nix/scripts/` inside a project is fine and encouraged. Registering a name that
        \\   already exists REPOINTS it and forgets the path it had, so check
        \\   `nix --list` first and pick an unused name. nix refuses this when it
        \\   cannot ask (your shell included); `--force` overrides that refusal
        \\   and is never yours to add.
        \\
        \\## Example phrasing
        \\
        \\> Done - I wired the build and added actions. From anywhere:
        \\> - `{[x]s} acme :test` - run the test suite
        \\> - `{[x]s} acme :deploy` - build and deploy
        \\> - `{[e]s} acme src/server.zig` - jump to the entry point
        \\> - `{[g]s} acme "TODO(auth)"` - find the follow-ups I left
        \\
    , .{
        .table = try commandTable(arena, cfg),
        .o = config.shortcutFor(cfg, "o"),
        .e = config.shortcutFor(cfg, "e"),
        .s = config.shortcutFor(cfg, "s"),
        .y = config.shortcutFor(cfg, "y"),
        .p = config.shortcutFor(cfg, "p"),
        .x = config.shortcutFor(cfg, "x"),
        .g = config.shortcutFor(cfg, "g"),
        .f = config.shortcutFor(cfg, "f"),
        .q = config.shortcutFor(cfg, "q"),
        .n = config.shortcutFor(cfg, "n"),
    });
    return b.items;
}

test "render: the {args} placeholder survives the format pass" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const out = try render(arena_state.allocator(), .{});
    // It is written `{{args}}` in the template; a slip there would put a stray
    // brace in every generated guide on every machine.
    try std.testing.expect(std.mem.indexOf(u8, out, "`{args}` placeholder") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "{{args}}") == null);
}

test "render uses default names" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const out = try render(arena_state.allocator(), .{});
    try std.testing.expect(std.mem.indexOf(u8, out, "| `o <alias> [path]` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`x <alias> :<name>`") != null);
    // The table carries the safety tier, and the guide points at the specs.
    try std.testing.expect(std.mem.indexOf(u8, out, "| user-surface |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`<cmd> --agent`") != null);
}

test "render honours [shortcuts] renames" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const cfg = config.Config{ .shortcuts = &.{
        .{ .builtin = "s", .custom = "show" },
        .{ .builtin = "x", .custom = "run" },
    } };
    const out = try render(arena_state.allocator(), cfg);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `show <alias> [pat]` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `run <alias> <cmd...>` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`run acme :deploy`") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `s <alias>") == null);
}
