//! ~/.nix/AGENTS.md generation — an agent-facing guide to the installed
//! command surface, written by --init/--sync alongside the shell snippet.
//!
//! The guide is an *installed artifact*, deliberately not a repo-level
//! AGENTS.md: repo files are auto-read by agent tools the moment a stranger
//! clones, which is the wrong consent model for machine-wide instructions
//! (and reads as prompt injection). Written by --init, it exists only on
//! machines whose owner installed nix, and --sync keeps it honest about
//! [shortcuts] renames. nix never wires it into any agent's config — the
//! README shows the one-line import users add themselves.

const std = @import("std");
const Io = std.Io;
const config = @import("config.zig");
const util = @import("util.zig");

pub fn path(arena: std.mem.Allocator, home: []const u8) ![]const u8 {
    return std.fs.path.join(arena, &.{ home, "AGENTS.md" });
}

pub fn write(arena: std.mem.Allocator, io: Io, home: []const u8, cfg: config.Config) !void {
    const p = try path(arena, home);
    try util.writeFileAtomic(arena, io, p, try render(arena, cfg));
}

/// render produces the guide with the machine's effective command names, so a
/// `[shortcuts] s = "show"` rename shows agents `show acme`, not a dead `s`.
pub fn render(arena: std.mem.Allocator, cfg: config.Config) ![]const u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.print(arena,
        \\<!-- Generated by `nix --sync`; edits are overwritten. Command names
        \\     reflect this machine's config.toml [shortcuts]. -->
        \\
        \\# nix directory aliases — agent guide
        \\
        \\The user of this machine navigates with [nix](https://github.com/sadirano/nix),
        \\a directory alias manager: projects get short aliases, and navigation,
        \\running, searching, and file movement go through them. When telling the user
        \\how to open, run, or find something, prefer the nix syntax below over raw
        \\cd/absolute-path instructions — e.g. "I added a deploy action; run it with
        \\`{[r]s} acme :deploy`".
        \\
        \\## Commands (what the user types)
        \\
        \\| Command | Meaning |
        \\|---|---|
        \\| `{[o]s} <alias>` | cd into the alias dir (current shell) |
        \\| `{[e]s} <alias> [file]` | open the dir (or a file) in the editor |
        \\| `{[s]s} <alias> [pat]` | open in the file manager; with a pattern, pick files to open with default apps |
        \\| `{[y]s} <alias> [pat]` | copy the path; with a pattern, pick files and copy the files themselves |
        \\| `{[p]s} <alias> [name]` | save clipboard contents (text/image/copied files) into the alias dir |
        \\| `{[r]s} <alias> <cmd…>` | run a command in the alias dir |
        \\| `{[r]s} <alias> :<name>` | run a saved action (`{[r]s} <alias> :` lists them) |
        \\| `{[sg]s} <alias> <pat>` | ripgrep search under the dir (fzf picker; `--all` reaches into PDFs/docs) |
        \\| `{[ff]s} <alias> [pat]` | fuzzy-find files under the dir |
        \\
        \\Extras: `{[o]s} docs@acme` resolves a sub-alias segment; `+group` fans a command
        \\across a set of aliases (`{[r]s} +work git pull`); `nix <name> <path>` registers
        \\a new alias.
        \\
        \\## Guidance for agents
        \\
        \\1. **Suggest nix forms.** When work produces something runnable or openable,
        \\   give the user the nix one-liner: `{[r]s} <alias> :test`,
        \\   `{[e]s} <alias> src/main.zig`, `{[s]s} <alias> report.pdf`, `{[sg]s} <alias> TODO`.
        \\2. **Discover aliases before suggesting.** `nix --list` prints every alias
        \\   with its path; `nix --list-names` prints bare names; `nix <alias>` resolves
        \\   one to its absolute path; `nix --which [path]` prints the alias containing
        \\   a path (default: cwd) — and inside a `{[r]s}`/`{[o]s}` session `$NIX_ALIAS` /
        \\   `$NIX_ALIAS_PATH` are already set. Use the alias that maps to the directory
        \\   you worked in — don't invent names. If none covers it, suggest registering
        \\   one: `nix <name> <path>`.
        \\3. **Prefer saved actions for repeatable commands.** If a project needs a
        \\   recurring build/test/serve/deploy command, add it to the project's
        \\   `.nix/actions.toml` under `[actions]` and point the user at
        \\   `{[r]s} <alias> :<name>`. Full scripts go in the project's `.nix/scripts/`
        \\   and run by bare name: `{[r]s} <alias> build`. Personal machine-wide
        \\   actions live in `~/.nix/actions/_default.toml` (lowest precedence,
        \\   available via `{[r]s} <any-alias> :<name>`). A tool the project
        \\   builds that should be runnable from anywhere goes under `[bin]` in
        \\   the same actions.toml (e.g. `hoot = "zig-out/bin/hoot.exe"`);
        \\   `nix --sync-bin` installs it into `~/.nix/bin`, which is on PATH.
        \\4. **In your own shell, resolve — don't `{[o]s}`.** `{[o]s}` is shell glue that
        \\   cds the user's interactive shell; in an agent's shell run `nix <alias>`
        \\   to get the path, then use the absolute path. `{[r]s} <alias> <cmd>` works
        \\   fine from agent shells.
        \\5. **Don't run the interactive pickers.** `{[sg]s}`, `{[ff]s}`, patterned
        \\   `{[s]s}`/`{[y]s}`, `{[o]s} +group`, and `nix --prune`/`--sweep` open fzf and block a
        \\   non-interactive shell. Suggest them to the user; use plain `rg`/`fd`
        \\   against the resolved path yourself.
        \\6. **Don't touch nix state destructively.** Never edit or delete `~/.nix`
        \\   contents (`aliases.toml`, `groups.toml`, `usage`, …) unless explicitly
        \\   asked; adding a project-local `.nix/actions.toml` or `.nix/scripts/`
        \\   inside a project is fine and encouraged.
        \\
        \\## Example phrasing
        \\
        \\> Done — I wired the build and added actions. From anywhere:
        \\> - `{[r]s} acme :test` — run the test suite
        \\> - `{[r]s} acme :deploy` — build and deploy
        \\> - `{[e]s} acme src/server.zig` — jump to the entry point
        \\> - `{[sg]s} acme "TODO(auth)"` — find the follow-ups I left
        \\
    , .{
        .o = config.shortcutFor(cfg, "o"),
        .e = config.shortcutFor(cfg, "e"),
        .s = config.shortcutFor(cfg, "s"),
        .y = config.shortcutFor(cfg, "y"),
        .p = config.shortcutFor(cfg, "p"),
        .r = config.shortcutFor(cfg, "r"),
        .sg = config.shortcutFor(cfg, "sg"),
        .ff = config.shortcutFor(cfg, "ff"),
    });
    return b.items;
}

test "render uses default names" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const out = try render(arena_state.allocator(), .{});
    try std.testing.expect(std.mem.indexOf(u8, out, "| `o <alias>` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`r <alias> :<name>`") != null);
}

test "render honours [shortcuts] renames" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const cfg = config.Config{ .shortcuts = &.{
        .{ .builtin = "s", .custom = "show" },
        .{ .builtin = "r", .custom = "run" },
    } };
    const out = try render(arena_state.allocator(), cfg);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `show <alias> [pat]` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "`run acme :deploy`") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "| `s <alias>") == null);
}
