//! Shell-integration generation. On Windows nix ships as a multi-call binary:
//! the same exe is installed into ~/.nix/bin under each command name (o, e, …)
//! and recovers the action from argv[0]; with ~/.nix/bin on the persistent
//! user PATH (winpath.zig) no shell snippet or $PROFILE glue is needed.
//! POSIX keeps the shell-function snippet model (cd in place + completion).

const std = @import("std");
const builtin = @import("builtin");
const Io = std.Io;
const config = @import("config.zig");
const agents = @import("agents.zig");
const util = @import("util.zig");
const store = @import("store.zig");
const actions = @import("actions.zig");
const mkdirAll = util.mkdirAll;

const is_windows = builtin.os.tag == .windows;

/// wrappersManifestPath: <home>/wrappers.toml — the last-installed set of
/// resolved wrapper names, so a later sync can tell a name apart that's no
/// longer any slot's effective name (a custom rename replaced by another
/// custom rename) from an unrelated file sharing bin/ — a [bin] export like
/// hoot.exe must never be swept just for being an unrecognized .exe there.
pub fn wrappersManifestPath(arena: std.mem.Allocator, home: []const u8) ![]const u8 {
    return std.fs.path.join(arena, &.{ home, "wrappers.toml" });
}

fn loadWrapperManifest(arena: std.mem.Allocator, io: Io, home: []const u8) ![]actions.Action {
    const p = try wrappersManifestPath(arena, home);
    const data = Io.Dir.cwd().readFileAlloc(io, p, arena, .unlimited) catch |e| switch (e) {
        error.FileNotFound => return &.{},
        else => return e,
    };
    return actions.parseTable(arena, data, "wrappers");
}

fn saveWrapperManifest(arena: std.mem.Allocator, io: Io, home: []const u8, names: []const []const u8) !void {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(arena, "# nix wrapper names — generated by `nix --sync`; do not edit.\n# lets a later sync drop a name no longer in use ([shortcuts] renamed away).\n\n[wrappers]\n");
    for (names) |n| {
        try b.appendSlice(arena, n);
        try b.appendSlice(arena, " = ");
        try store.appendTomlString(arena, &b, n);
        try b.append(arena, '\n');
    }
    try util.writeFileAtomic(arena, io, try wrappersManifestPath(arena, home), b.items);
}

pub fn bashPath(arena: std.mem.Allocator, home: []const u8) ![]const u8 {
    return std.fs.path.join(arena, &.{ home, "shell", "nix.sh" });
}

/// regenerate loads config and installs the platform integration: exe wrappers
/// on Windows, the shell-function snippet elsewhere. exe is the absolute path
/// to the running nix binary.
/// Returns the wrapper names left STALE on disk — a running wrapper is
/// normally replaced by renaming its live image aside, so this is only the
/// double-failure case (even the rename refused) — callers must surface
/// these, or the old binary silently keeps answering to that name.
pub fn regenerate(arena: std.mem.Allocator, io: Io, home: []const u8, exe: []const u8) ![]const []const u8 {
    const cfg = try config.loadConfig(arena, io, home);
    try agents.write(arena, io, home, cfg);
    const names = try config.resolvedShortcutNames(arena, cfg);
    if (is_windows) {
        // Builtin slot names renamed away in [shortcuts] leave their old
        // wrapper exes behind — collect them so --sync deletes them, or the
        // stale `s.exe` keeps answering after a rename to `show`. A builtin
        // name still claimed by ANY slot's effective name is kept (swaps).
        var renamed_away: std.ArrayList([]const u8) = .empty;
        for (config.builtinShortcuts()) |bsc| {
            var in_use = false;
            for (names) |n| if (std.ascii.eqlIgnoreCase(n, bsc.builtin)) {
                in_use = true;
                break;
            };
            if (!in_use) try renamed_away.append(arena, bsc.builtin);
        }
        // A custom name renamed away to ANOTHER custom name (e.g. sg="g" then
        // sg="gg") isn't a builtin, so the loop above never sees it — only the
        // wrapper manifest remembers "g" was installed last time. Fold those
        // into the same delete pass.
        const prev = try loadWrapperManifest(arena, io, home);
        for (prev) |p| {
            var still_in_use = false;
            for (names) |n| if (std.ascii.eqlIgnoreCase(n, p.name)) {
                still_in_use = true;
                break;
            };
            if (still_in_use) continue;
            var already_queued = false;
            for (renamed_away.items) |r| if (std.ascii.eqlIgnoreCase(r, p.name)) {
                already_queued = true;
                break;
            };
            if (!already_queued) try renamed_away.append(arena, p.name);
        }
        const bin = try std.fs.path.join(arena, &.{ home, "bin" });
        const stale = try installExeWrappers(arena, io, bin, exe, names, renamed_away.items);
        try saveWrapperManifest(arena, io, home, names);
        return stale;
    }
    try writeBash(arena, io, home, exe, cfg);
    return &.{};
}

fn writeBash(arena: std.mem.Allocator, io: Io, home: []const u8, exe: []const u8, cfg: config.Config) !void {
    const path = try bashPath(arena, home);
    if (std.fs.path.dirname(path)) |d| try mkdirAll(io, d);
    const names = try config.resolvedShortcutNames(arena, cfg);
    // Resolve individual slot names for the function bodies.
    const o = config.shortcutFor(cfg, "o");
    const e = config.shortcutFor(cfg, "e");
    const s = config.shortcutFor(cfg, "s");
    const y = config.shortcutFor(cfg, "y");
    const p = config.shortcutFor(cfg, "p");
    const r = config.shortcutFor(cfg, "r");
    const sg = config.shortcutFor(cfg, "sg");
    const ff = config.shortcutFor(cfg, "ff");

    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(arena, "# nix shell integration (generated; do not edit — run 'nix --sync')\n");
    try b.print(arena, "export NIX_EXE='{s}'\n\n", .{exe});
    try b.appendSlice(arena,
        \\if [ -n "$BASH_VERSION" ]; then
        \\    _nix_completer() {
        \\        local cur=${COMP_WORDS[COMP_CWORD]}
        \\        local names
        \\        mapfile -t names < <("$NIX_EXE" --list-names 2>/dev/null)
        \\        COMPREPLY=( $(compgen -W "${names[*]}" -- "$cur") )
        \\    }
        \\elif [ -n "$ZSH_VERSION" ] && command -v compdef >/dev/null 2>&1; then
        \\    _nix_zsh_completer() {
        \\        local line names=()
        \\        while IFS= read -r line; do
        \\            names+=("$line")
        \\        done < <("$NIX_EXE" --list-names 2>/dev/null)
        \\        compadd -- "${names[@]}"
        \\    }
        \\fi
        \\
        \\
    );
    try b.print(arena,
        \\{s}() {{
        \\    if [ -z "$1" ]; then
        \\        "$NIX_EXE" --edit
        \\        return
        \\    fi
        \\    local path
        \\    path=$("$NIX_EXE" "$@")
        \\    if [ $? -eq 0 ]; then
        \\        cd "$path"
        \\    fi
        \\}}
        \\
    , .{o});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --edit \"$@\"; }}\n", .{e});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --explore \"$@\"; }}\n", .{s});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --yank \"$@\"; }}\n", .{y});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --paste \"$@\"; }}\n", .{p});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --run \"$@\"; }}\n", .{r});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --grep \"$@\"; }}\n", .{sg});
    try b.print(arena, "{s}() {{ local alias=$1; shift; \"$NIX_EXE\" \"$alias\" --find \"$@\"; }}\n\n", .{ff});

    var joined: std.ArrayList(u8) = .empty;
    for (names, 0..) |n, i| {
        if (i > 0) try joined.append(arena, ' ');
        try joined.appendSlice(arena, n);
    }
    try b.print(arena,
        \\if [ -n "$BASH_VERSION" ]; then
        \\    complete -F _nix_completer {s}
        \\elif [ -n "$ZSH_VERSION" ] && command -v compdef >/dev/null 2>&1; then
        \\    compdef _nix_zsh_completer {s}
        \\fi
        \\
    , .{ joined.items, joined.items });
    try util.writeFileAtomic(arena, io, path, b.items);
}

/// installExeWrappers makes nix available under each command name in binDir by
/// copying the canonical nix exe to bin/nix.exe and to each wrapper name. (onix
/// hardlinks; nix copies — simpler, functionally equivalent, just more disk.)
/// A wrapper backing a live session is replaced via rename-aside (see
/// writeExeAtomic). Returns the names whose wrapper STILL could not be
/// replaced AND whose on-disk copy differs from the new binary — those keep
/// answering with the OLD version until updated.
fn installExeWrappers(arena: std.mem.Allocator, io: Io, bin: []const u8, exe: []const u8, names: [][]const u8, renamed_away: []const []const u8) ![]const []const u8 {
    try mkdirAll(io, bin);
    sweepStale(arena, io, bin);
    const ext = if (is_windows) ".exe" else "";
    // Renamed-away builtin wrappers: delete so the old name stops answering.
    // Best-effort — a locked (running) exe stays until the next sync.
    for (renamed_away) |name| {
        const dst = try std.fmt.allocPrint(arena, "{s}{c}{s}{s}", .{ bin, std.fs.path.sep, name, ext });
        Io.Dir.cwd().deleteFile(io, dst) catch {};
    }
    const canonical = try std.fmt.allocPrint(arena, "{s}{c}nix{s}", .{ bin, std.fs.path.sep, ext });
    if (!samePath(canonical, exe)) {
        const data = try Io.Dir.cwd().readFileAlloc(io, exe, arena, .unlimited);
        try writeExeAtomic(arena, io, canonical, data);
    }
    const data = try Io.Dir.cwd().readFileAlloc(io, canonical, arena, .unlimited);
    var stale: std.ArrayList([]const u8) = .empty;
    for (names) |name| {
        const dst = try std.fmt.allocPrint(arena, "{s}{c}{s}{s}", .{ bin, std.fs.path.sep, name, ext });
        if (samePath(dst, canonical)) continue;
        writeExeAtomic(arena, io, dst, data) catch {
            // Locked (a running wrapper can't be replaced on Windows). If the
            // bytes on disk already match, it's merely busy, not stale.
            const existing = Io.Dir.cwd().readFileAlloc(io, dst, arena, .unlimited) catch "";
            if (!std.mem.eql(u8, existing, data)) try stale.append(arena, name);
            continue;
        };
    }
    return stale.items;
}

/// writeExeAtomic writes an exe via a private temp + rename, so an interrupted
/// --sync can never leave a half-written binary answering on PATH (a torn
/// wrapper is worse than a stale one). A locked destination (a RUNNING exe —
/// Windows denies writing its image but allows renaming it) is moved aside to
/// `<dst>.<rand>.stale` and the new file lands in its place: live sessions
/// keep executing the renamed image, every new invocation gets the new build,
/// and later syncs sweep the leftovers once they unlock. Only when even the
/// move-aside fails does the temp get removed and the error propagate to the
/// caller's stale check.
fn writeExeAtomic(arena: std.mem.Allocator, io: Io, dst: []const u8, data: []const u8) !void {
    const tmp = try util.uniqueTmpName(arena, io, dst);
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = tmp, .data = data });
    Io.Dir.cwd().rename(tmp, Io.Dir.cwd(), dst, io) catch |first_err| {
        // Busy but already current: a live session on the NEW build is not a
        // replacement problem — don't park its image on every sync.
        const existing = Io.Dir.cwd().readFileAlloc(io, dst, arena, .unlimited) catch "";
        if (std.mem.eql(u8, existing, data)) {
            Io.Dir.cwd().deleteFile(io, tmp) catch {};
            return;
        }
        const aside = asideName(arena, io, dst) catch {
            Io.Dir.cwd().deleteFile(io, tmp) catch {};
            return first_err;
        };
        moveFile(arena, io, dst, aside) catch {
            Io.Dir.cwd().deleteFile(io, tmp) catch {};
            return first_err;
        };
        Io.Dir.cwd().rename(tmp, Io.Dir.cwd(), dst, io) catch |e| {
            // The slot is now EMPTY — put the old image back rather than leave
            // the name answering to nothing.
            moveFile(arena, io, aside, dst) catch {};
            Io.Dir.cwd().deleteFile(io, tmp) catch {};
            return e;
        };
    };
}

extern "kernel32" fn MoveFileExW(lpExistingFileName: [*:0]const u16, lpNewFileName: ?[*:0]const u16, dwFlags: u32) callconv(.winapi) i32;

/// moveFile renames via MoveFileExW on Windows: the Io.Dir.rename path opens
/// the source with access a RUNNING exe's image lock denies (FileBusy), while
/// MoveFileExW performs the same-volume rename the OS explicitly permits for
/// live images — the whole point of the move-aside strategy. POSIX renames
/// have no such lock and use the portable path.
fn moveFile(arena: std.mem.Allocator, io: Io, from: []const u8, to: []const u8) !void {
    if (!is_windows) return Io.Dir.cwd().rename(from, Io.Dir.cwd(), to, io);
    const from_w = try std.unicode.utf8ToUtf16LeAllocZ(arena, from);
    const to_w = try std.unicode.utf8ToUtf16LeAllocZ(arena, to);
    if (MoveFileExW(from_w.ptr, to_w.ptr, 0) == 0) return error.MoveFileFailed;
}

/// asideName is uniqueTmpName's sibling for parked live images: a random
/// suffix keeps concurrent syncs apart, and the fixed ".stale" tail is what
/// sweepStale and the doctor's undeclared-file scan key on.
fn asideName(arena: std.mem.Allocator, io: Io, path: []const u8) ![]const u8 {
    var b: [8]u8 = undefined;
    io.random(&b);
    return std.fmt.allocPrint(arena, "{s}.{x}.stale", .{ path, std.mem.readInt(u64, &b, .little) });
}

/// sweepStale deletes parked `.stale` images left by earlier syncs. Best
/// effort: one still backing a live session stays locked and simply survives
/// to the next sweep.
fn sweepStale(arena: std.mem.Allocator, io: Io, bin: []const u8) void {
    var dir = Io.Dir.cwd().openDir(io, bin, .{ .iterate = true }) catch return;
    defer dir.close(io);
    var it = dir.iterate();
    while (it.next(io) catch null) |ent| {
        if (ent.kind == .directory) continue;
        if (!std.ascii.endsWithIgnoreCase(ent.name, ".stale")) continue;
        const p = std.fs.path.join(arena, &.{ bin, ent.name }) catch continue;
        Io.Dir.cwd().deleteFile(io, p) catch {};
    }
}

fn samePath(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) return false;
    if (is_windows) {
        for (a, b) |x, y| if (std.ascii.toLower(x) != std.ascii.toLower(y)) return false;
        return true;
    }
    return std.mem.eql(u8, a, b);
}
